### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by balachandranc** [simongeilfus/Cinder-Cereal#1]
Hi,

I am unable to compile the sample given in the project. Attaching the output of the build below:

1>------ Build started: Project: Cereal, Configuration: Release Win32 ------
1>  CerealApp.cpp
1>C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(456): error C2338: cereal could not find any output serialization functions for the provided type and archive combination.
1>  
1>   Types must either have a serialize function, load/save pair, or load_minimal/save_minimal pair (you may not mix these). 
1>   Serialize functions generally have the following signature: 
1>  
1>   template<class Archive> 
1>     void serialize(Archive & ar) 
1>     { 
1>       ar( member1, member2, member3 ); 
1>     } 
1>  
1>  
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(333) : see reference to function template instantiation 'ArchiveType &cereal::OutputArchive<ArchiveType,0>::processImpl<T,0>(const T &)' being compiled
1>          with
1>          [
1>              ArchiveType=cereal::JSONOutputArchive
1>  ,            T=cinder::Area
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(333) : see reference to function template instantiation 'ArchiveType &cereal::OutputArchive<ArchiveType,0>::processImpl<T,0>(const T &)' being compiled
1>          with
1>          [
1>              ArchiveType=cereal::JSONOutputArchive
1>  ,            T=cinder::Area
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(341) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<_Ty>(T &&)' being compiled
1>          with
1>          [
1>              _Ty=cinder::Area
1>  ,            T=cinder::Area
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(341) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<_Ty>(T &&)' being compiled
1>          with
1>          [
1>              _Ty=cinder::Area
1>  ,            T=cinder::Area
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(342) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<_Ty,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=cinder::Area
1>  ,            T=cinder::Area
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(342) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<_Ty,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=cinder::Area
1>  ,            T=cinder::Area
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(342) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<_Ty,cinder::Area,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T &&,cinder::Area &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=cereal::NameValuePair<cinder::CameraPersp &>
1>  ,            T=cereal::NameValuePair<cinder::CameraPersp &>
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(342) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<_Ty,cinder::Area,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T &&,cinder::Area &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=cereal::NameValuePair<cinder::CameraPersp &>
1>  ,            T=cereal::NameValuePair<cinder::CameraPersp &>
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(342) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<_Ty,cereal::NameValuePair<cinder::CameraPersp &>,cinder::Area,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T &&,cereal::NameValuePair<cinder::CameraPersp &> &&,cinder::Area &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::vec3> &>
1>  ,            T=cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::vec3> &>
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(342) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<_Ty,cereal::NameValuePair<cinder::CameraPersp &>,cinder::Area,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T &&,cereal::NameValuePair<cinder::CameraPersp &> &&,cinder::Area &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::vec3> &>
1>  ,            T=cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::vec3> &>
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(342) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<bool(&)[2],_Ty,cereal::NameValuePair<cinder::CameraPersp &>,cinder::Area,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T,_Ty &&,cereal::NameValuePair<cinder::CameraPersp &> &&,cinder::Area &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::vec3> &>
1>  ,            T=bool (&)[2]
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(342) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::process<bool(&)[2],_Ty,cereal::NameValuePair<cinder::CameraPersp &>,cinder::Area,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T,_Ty &&,cereal::NameValuePair<cinder::CameraPersp &> &&,cinder::Area &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::vec3> &>
1>  ,            T=bool (&)[2]
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(249) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::processstd::vector<GLint,std::allocator<_Ty>&,bool(&)[2],cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::tvec3<float,0>> &>,cereal::NameValuePair<cinder::CameraPersp &>,cinder::Area,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T,bool (&)[2],cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::tvec3<float,0>> &> &&,cereal::NameValuePair<cinder::CameraPersp &> &&,cinder::Area &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=GLint
1>  ,            T=std::vector<GLint,std::allocator<GLint>> &
1>          ]
1>          C:\dev\cinder_0.9.0_vc2013\blocks\Cinder-Cereal\samples\Cereal\include\cereal/cereal.hpp(249) : see reference to function template instantiation 'void cereal::OutputArchivecereal::JSONOutputArchive,0::processstd::vector<GLint,std::allocator<_Ty>&,bool(&)[2],cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::tvec3<float,0>> &>,cereal::NameValuePair<cinder::CameraPersp &>,cinder::Area,glm::tvec2<int,0>,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(T,bool (&)[2],cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::tvec3<float,0>> &> &&,cereal::NameValuePair<cinder::CameraPersp &> &&,cinder::Area &&,glm::tvec2<int,0> &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              _Ty=GLint
1>  ,            T=std::vector<GLint,std::allocator<GLint>> &
1>          ]
1>          ..\src\CerealApp.cpp(31) : see reference to function template instantiation 'ArchiveType &cereal::OutputArchive<ArchiveType,0>::operator ()std::vector<GLint,std::allocator<_Ty>&,bool(&)[2],cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::tvec3<float,0>> &>,cereal::NameValuePair<cinder::CameraPersp &>,cinder::Area,glm::ivec2,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(std::vector<_Ty,std::allocator<_Ty>> &,bool (&)[2],cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::tvec3<float,0>> &> &&,cereal::NameValuePair<cinder::CameraPersp &> &&,cinder::Area &&,glm::ivec2 &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              ArchiveType=cereal::JSONOutputArchive
1>  ,            _Ty=GLint
1>          ]
1>          ..\src\CerealApp.cpp(31) : see reference to function template instantiation 'ArchiveType &cereal::OutputArchive<ArchiveType,0>::operator ()std::vector<GLint,std::allocator<_Ty>&,bool(&)[2],cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::tvec3<float,0>> &>,cereal::NameValuePair<cinder::CameraPersp &>,cinder::Area,glm::ivec2,boost::filesystem::path&,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>>&>(std::vector<_Ty,std::allocator<_Ty>> &,bool (&)[2],cereal::NameValuePairstd::vector<glm::vec3,std::allocator<glm::tvec3<float,0>> &> &&,cereal::NameValuePair<cinder::CameraPersp &> &&,cinder::Area &&,glm::ivec2 &&,boost::filesystem::path &,std::vectorstd::string,std::allocator<std::basic_string<char,std::char_traits<char,std::allocator<char>>>> &)' being compiled
1>          with
1>          [
1>              ArchiveType=cereal::JSONOutputArchive
1>  ,            _Ty=GLint
1>          ]
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by balachandranc** [comment]
Moving the definitions in CinderCereal.h into namespace cereal solved the issue.

**Comment by simongeilfus** [comment]
Thanks for pointing that out! For some reason XCode didn't complain about it.
Should be fixed in this commit: https://github.com/simongeilfus/Cinder-Cereal/commit/c28eda89125b9ee2b69f5fca292d412594099182
